---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16021.
--- DateTime: 2024/2/1 18:59
---
table.insert(editor_objlist_order, "text_lost")
table.insert(editor_objlist_order, "text_find")
table.insert(editor_objlist_order, "text_missing")
table.insert(editor_objlist_order, "text_greedy")
table.insert(editor_objlist_order, "text_prop")

editor_objlist["text_greedy"] = {
    name = "text_greedy",
    sprite_in_root = false,
    unittype = "text",
    tags = { "text_quality", "text_special" },
    tiling = -1,
    type = 2,
    layer = 20,
    colour = { 3, 0 },
    colour_active = { 3, 1 },
}
editor_objlist["text_prop"] = {
    name = "text_prop",
    sprite_in_root = false,
    unittype = "text",
    tags = { "text_quality", "text_special" },
    tiling = -1,
    type = 2,
    layer = 20,
    colour = { 2, 2 },
    colour_active = { 2, 3 },
}

editor_objlist["text_lost"] = {
    name = "text_lost",
    sprite_in_root = false,
    unittype = "text",
    tags = { "text", "abstract" },
    tiling = -1,
    type = 2,
    layer = 0,
    colour = { 5, 1 },
    colour_active = { 5, 2 },
}

editor_objlist["text_find"] = {
    name = "text_find",
    sprite_in_root = false,
    unittype = "text",
    tags = { "text", "abstract" },
    tiling = -1,
    type = 2,
    layer = 0,
    colour = { 4, 0 },
    colour_active = { 4, 1 },
}

editor_objlist["text_missing"] = {
    name = "text_missing",
    sprite_in_root = false,
    unittype = "text",
    tags = { "text", "abstract" },
    tiling = -1,
    type = 3,
    layer = 0,
    colour = { 5, 1 },
    colour_active = { 5, 2 },
}

formatobjlist()
